# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path

project_root = Path(SPECPATH).resolve().parent

block_cipher = None

# ===== 隐藏导入 =====
hiddenimports = [
    'openpyxl',
    'openpyxl.cell',
    'openpyxl.reader',
    'openpyxl.workbook',
    'openpyxl.writer',
    'openpyxl.styles',
    'openpyxl.styles.numbers',
    'openpyxl.utils',
    'openpyxl.utils.cell',
    'openpyxl.formula',
    'openpyxl.comments',
    'openpyxl.drawing',
    'openpyxl.chart',
    'openpyxl.worksheet',
    'openpyxl.worksheet.cell_range',
    'openpyxl.packaging',
    'openpyxl.xml',
    'openpyxl.xml.functions',
    'pandas',
    'pandas.io',
    'pandas.io.excel',
    'pandas.core',
    'pandas.core.frame',
    'pandas.core.series',
    'pandas.core.indexes',
    'pandas.core.dtypes',
    'pandas.core.algorithms',
    'pandas.core.arrays',
    'pandas.core.groupby',
    'pandas.core.reshape',
    'pandas.core.sorting',
    'pandas.core.window',
    'pandas.io.common',
    'pandas.io.parsers',
    'pandas.io.parsers.readers',
    'numpy',
    'numpy.core',
    'numpy.core._methods',
    'numpy.lib',
    'numpy.lib.format',
    'numpy.random',
    'numpy.random._common',
    'numpy.linalg',
    'numpy.linalg.linalg',
    'numpy.fft',
    'numpy.polynomial',
    'numpy.ma',
    'numpy.matrixlib',
    'numpy.rec',
    'numpy.testing',
    'yaml',
    'yaml.loader',
    'yaml.dumper',
    'lxml',
    'lxml.etree',
    'lxml._elementpath',
    'PyQt5',
    'PyQt5.QtCore',
    'PyQt5.QtWidgets',
    'PyQt5.QtGui',
    'decimal',
    'datetime',
    'pathlib',
    'logging',
    'traceback',
    're',
    'copy',
    'shutil',
    'tempfile',
    'argparse',
    'enum',
    'dataclasses',
    'KingdeeZwyCashFlowGenerator',
    'KingdeeZwyCashFlowGenerator.app.desktop',
    'KingdeeZwyCashFlowGenerator.cli',
    'KingdeeZwyCashFlowGenerator.configuration.settings',
    'KingdeeZwyCashFlowGenerator.core.generator',
    'KingdeeZwyCashFlowGenerator.core.paths',
    'KingdeeZwyCashFlowGenerator.core.reporter_factory',
    'KingdeeZwyCashFlowGenerator.domain.transactions',
    'KingdeeZwyCashFlowGenerator.domain.reports',
    'KingdeeZwyCashFlowGenerator.ledger.loader',
    'KingdeeZwyCashFlowGenerator.ledger.validator',
    'KingdeeZwyCashFlowGenerator.classification.classifier',
    'KingdeeZwyCashFlowGenerator.classification.strategy',
    'KingdeeZwyCashFlowGenerator.classification.defaults',
    'KingdeeZwyCashFlowGenerator.quarter.mapper',
    'KingdeeZwyCashFlowGenerator.quarter.merger',
    'KingdeeZwyCashFlowGenerator.reporting.aggregator',
    'KingdeeZwyCashFlowGenerator.reporting.writer',
    'KingdeeZwyCashFlowGenerator.reporting.sheet_filler',
    'KingdeeZwyCashFlowGenerator.reporting.template_builder',
    'KingdeeZwyCashFlowGenerator.reporting.summary',
]

# ===== 资源文件 =====
datas = [
    (str(project_root / 'resources' / 'templates'), 'resources/templates'),
    (str(project_root / 'config' / 'config.yaml'), 'config'),
]

# ===== 如果有图标文件，添加到这里 =====
# 图标文件位于 resources 目录

a = Analysis(
    [str(project_root / 'scripts' / 'run' / 'launch.py')],
    pathex=[str(project_root)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'PIL',
        'tkinter',
        'test',
        'tests',
        'unittest',
        'distutils',
        'setuptools',
        'ipython',
        'jupyter',
        'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ===== 可执行文件配置 =====
exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='现金流量报表生成器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # True=显示控制台窗口，False=不显示
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(project_root / 'resources' / 'icon.ico'),
)
